### ISSUE TITLE
Add PixelBits to sponsors

### ISSUE THREAD

**Issue by joshghent** [leicesterjs/site#15]
@dave-irvine can provide you with the details and logo

**Comment by dave-irvine** [comment]
![logo-no_text_large](https://user-images.githubusercontent.com/1782643/64237622-9e054b80-cef4-11e9-90fc-c6a1a8bd65a8.png)
![logo_color](https://user-images.githubusercontent.com/1782643/64237635-a52c5980-cef4-11e9-952d-9af94e110896.png)

**Comment by danjordan** [comment]
@dave-irvine Do you have a website?

I'll add logos in the future, we may need some design love on this one too.

**Comment by dave-irvine** [comment]
@danjordan No website at the moment (the irony).

**Comment by danjordan** [comment]
Closed with #17
