### ISSUE TITLE
Improve our <head>

### ISSUE THREAD

**Issue by danjordan** [leicesterjs/site#24]
See if there are any of these that we could add to make the site super cool.

- https://htmlhead.dev/

**Comment by jessicaaddams** [comment]
I'll have a go at trying to add some bits and bobs! #firsttimerfriendlyyispls

**Comment by jessicaaddams** [comment]
I've added some bits, but I don't have permission to push a branch.

**Comment by danjordan** [comment]
Hi @jessicaaddams! Thanks for helping us out!

I'm not sure how to give you permission to push a branch. Do you think you could create a pull request?

Here's a link that should help you out with that https://guides.github.com/activities/forking/

Any questions feel free to shout. Thanks again!

**Comment by danjordan** [comment]
Hi @jessicaaddams 

I've added you to a team on GitHub so you should be able to push your branch once you've accepted the invite.

I don't think anyone is allowed to push to master, but please don't try 😂

**Comment by joshghent** [comment]
@jessicaaddams @danjordan - You should need to fork the repo and then do a PR that way please!

**Comment by Adam-STaC-Solutions** [comment]
@joshghent She has done the change... But then she went to Disney... She should be looking at this again on Monday.

**Comment by jessicaaddams** [comment]
...cannot deny.. it's always Disney. I've had a go and added some basics! It's in PR #43
