### ISSUE TITLE
Remove tags that are not needed

### ISSUE THREAD

**Issue by danjordan** [leicesterjs/site#25]
The HTML spec defines some tags as optional. We can remove these <3

https://google.github.io/styleguide/htmlcssguide.html#Optional_Tags

**Comment by Adam-STaC-Solutions** [comment]
Going to have a look, happy to move over if someone wants to claim as a first ticket, but dev's gonna dev.

**Comment by Adam-STaC-Solutions** [comment]
After reading that link..... *runs* 
Haven't seen this side of the spec before, but can't help but feel readability will suffer?

**Comment by danjordan** [comment]
Yeh, I should maybe have clarified this one a bit better.

I think we can remove `html`, `head` and `body` without sacrificing readability. The rest we should leave in.

**Comment by Adam-STaC-Solutions** [comment]
Found a StackOverflow article elaborating on this:
https://stackoverflow.com/questions/5641997/is-it-necessary-to-write-head-body-and-html-tags

**Comment by Adam-STaC-Solutions** [comment]
See PR #40 https://github.com/leicesterjs/site/pull/40
