### ISSUE TITLE
Add meta description

### ISSUE THREAD

**Issue by danjordan** [leicesterjs/site#4]
I ran lighthouse and it suggested to add a meta description.

There is probably some nice text on https://www.meetup.com/leicesterjs/ that we could use for this.

**Comment by ileshmistry** [comment]
Hi @danjordan I also saw this 🙌 , are we looking to also add in SEO and Accessibility elements like rel=no follow / referrer?

**Comment by danjordan** [comment]
I don't see any reason to add these, but if you could explain why you think they are necessary I'd be open to changing my mind.

**Comment by ileshmistry** [comment]
This is a good article to help describe why to add the 'rel' attribute in - https://searchenginelaws.com/seo/what-is-rel-noopener-noreferrer-tag/

**Comment by danjordan** [comment]
If we add any links using `target="_blank"` we will definitely use `rel="noopener noreferrer"`. At the moment we don't open any links in a new window so I don't think this is needed. Thanks for the article though!
