### ISSUE TITLE
Update slack link on the main page

### ISSUE THREAD

**Issue by joshghent** [leicesterjs/site#41]
Current one is inactive
Just change it to
`https://join.slack.com/t/leicesterjs/shared_invite/enQtNDMwODk0ODQ4NTE2LWUyZWI3NGZlZmY1YTdlNWZjNDY1ZDZhZWJlNjNjOTg1ODUzOWRmMDZlMWM2NjlkZjIzNWZjZDAxODc4N2U1MzE`

**Comment by RealMattOwen** [comment]
Here's a PR that does a little more than was asked for https://github.com/leicesterjs/site/pull/42 let me know if it's too much 🙈
