### ISSUE TITLE
Add bundlesize CI checks to the build process

### ISSUE THREAD

**Issue by joshghent** [leicesterjs/site#47]
https://github.com/siddharthkp/bundlesize

**Comment by RealMattOwen** [comment]
The current site doesn't generate a JS bundle, I can look into adding this check in case one is added in future? Also what size do we feel is appropriate?

**Comment by joshghent** [comment]
Huh no kidding, didn't realise it didn't generate any bundle. Thanks for the investigation, I'll close this off 👍
