### ISSUE TITLE
Meetup details need adding to the site for October

### ISSUE THREAD

**Issue by Adam-STaC-Solutions** [leicesterjs/site#84]
The meetup details are here:
https://www.meetup.com/leicesterjs/events/272955679/

**Comment by pip-white** [comment]
will give this a go

**Comment by Adam-STaC-Solutions** [comment]
Can we update the PR to match the new event details please?

**Comment by Adam-STaC-Solutions** [comment]
Merged

**Comment by jerometwell** [comment]
Hey amigos, 

This is fantastic ✨. Can we get some copy written for the homepage? even if it's just vague blurb for the time being, it's better than repeating the september stuff again. 

I was thinking something along the lines of
```
This month we'll be diving into the world of community projects! Expect a showcase of home-grown leicesterjs projects along with some general chatter surrounding the colourful landscape of open source and code collaboration in general.

Whether this is your first time or your 3rd, we'll be happy to have you. details Here: xxxxxxx
```

Might need a separate issue for this?
What do you think?

**Comment by Adam-STaC-Solutions** [comment]
I opened a new issue for this 👍 

#86 

Will copy over the info
