### ISSUE TITLE
Homepage update - October 2020 edition

### ISSUE THREAD

**Issue by Adam-STaC-Solutions** [leicesterjs/site#86]
Homepage needs details adding that correspond to this: https://www.meetup.com/leicesterjs/events/272955679/

**Comment by Adam-STaC-Solutions** [comment]
Extra info circa @jerometwell 

Hey amigos,

This is fantastic ✨. Can we get some copy written for the homepage? even if it's just vague blurb for the time being, it's better than repeating the september stuff again.

I was thinking something along the lines of

This month we'll be diving into the world of community projects! Expect a showcase of home-grown leicesterjs projects along with some general chatter surrounding the colourful landscape of open source and code collaboration in general.

Whether this is your first time or your 3rd, we'll be happy to have you. details Here: xxxxxxx
Might need a separate issue for this?
What do you think?

**Comment by pip-white** [comment]
I'm happy to do you this as well

**Comment by jerometwell** [comment]
All yours ✨
